spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messagerie
    username: postgres
    password: silimo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
